# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Django 1.11
          - django-version: "1.11.29"
            python-version: "3.5"
          - django-version: "1.11.29"
            python-version: "3.6"
          - django-version: "1.11.29"
            python-version: "3.7"
          # Django 2.0
          - django-version: "2.0.13"
            python-version: "3.5"
          - django-version: "2.0.13"
            python-version: "3.6"
          - django-version: "2.0.13"
            python-version: "3.7"
          # Django 2.1
          - django-version: "2.1.15"
            python-version: "3.5"
          - django-version: "2.1.15"
            python-version: "3.6"
          - django-version: "2.1.15"
            python-version: "3.7"
          # Django 2.2
          - django-version: "2.2.8"
            python-version: "3.5"
          - django-version: "2.2.8"
            python-version: "3.6"
          - django-version: "2.2.8"
            python-version: "3.7"
          - django-version: "2.2.8"
            python-version: "3.8"
          - django-version: "2.2.8"
            python-version: "3.9"
          # Django 3.0
          - django-version: "3.0.14"
            python-version: "3.6"
          - django-version: "3.0.14"
            python-version: "3.7"
          - django-version: "3.0.14"
            python-version: "3.8"
          - django-version: "3.0.14"
            python-version: "3.9"
          # Django 3.1
          - django-version: "3.1.14"
            python-version: "3.6"
          - django-version: "3.1.14"
            python-version: "3.7"
          - django-version: "3.1.14"
            python-version: "3.8"
          - django-version: "3.1.14"
            python-version: "3.9"
          # Django 3.2
          - django-version: "3.2.14"
            python-version: "3.6"
          - django-version: "3.2.14"
            python-version: "3.7"
          - django-version: "3.2.14"
            python-version: "3.8"
          - django-version: "3.2.14"
            python-version: "3.9"
          - django-version: "3.2.14"
            python-version: "3.10"
          # Django 4.0
          - django-version: "4.0.6"
            python-version: "3.8"
          - django-version: "4.0.6"
            python-version: "3.9"
          - django-version: "4.0.6"
            python-version: "3.10"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 coverage
    - name: Install Django version
      run: |
        python -m pip install "Django~=${{ matrix.django-version }}"
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with django-admin
      run: |
        echo "Python ${{ matrix.python-version }} -> Django ${{ matrix.django-version }}"
        PYTHONPATH=$PYTHONPATH:$PWD coverage run `which django-admin` test adminrestrict --settings=adminrestrict.test_settings
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3